### ISSUE TITLE
The idea behind this project is awesome

### ISSUE THREAD

**Issue by Sandile-Dev01** [MythicalTrashcan/Ludos#1]
I like the idea and the vision behind this project but I feel like the UI can be improved.

The button’s shadow and not contrasting colors are overwhelming.

I’d reckon putting icons with redirectory links inside them instead of width filling buttons with text.😃

**Comment by 1-Mythical** [comment]
I understand the button shadows are a bit much but I don't quite see the overwhelming part in no contrasting colors.

Icons would be the next perfect addition now that I just figured out how to add images easily. When you say "redirectory links", do you mean to make the game icon be clickable and redirect to the requested game?
